### ISSUE TITLE
support BCrypt password hashing

### ISSUE THREAD

**Issue by khajavi** [zio/zio-crypto#8]
we should add a new module to support password hashing algorithms.

**Comment by emarx** [comment]
Would be great to have password hashing implemented! Let's perhaps implement Argon2, however. BCrypt isn't recommended for new projects: https://medium.com/analytics-vidhya/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e

**Comment by khajavi** [comment]
> Would be great to have password hashing implemented! Let's perhaps implement Argon2, however. BCrypt isn't recommended for new projects: https://medium.com/analytics-vidhya/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e

Great article, Thank you.
So what is your idea, we shouldn't include BCrypt, Scrypt and PBKDF2 algorithms in zio-crypto?
Maybe it would better include these password hashing and use the same strategy you used for safe and unsafe algorithms.

**Comment by emarx** [comment]
I think the interfaces for password hashing may vary a bit, and certainly their installation methods will vary. In that case, we can publish a separate package for different password hashing algorithms in different zio services, and different zio packages. 

For example, with Argon2, I would use https://github.com/phxql/argon2-jvm, as it uses the PHC reference C solution. 

That lib has two installation methods: one that includes this C dependency directly, and one (recommended) where it is assumed that the lib is installed on the machine. We should probably have a "zio-crypto-argon-depfree" and a "zio-crypto-argon" package on Maven to expose this same choice. 

It also has three variants: one that's more CPU intensive (better for passwords), one that's more GPU intensive (better for cryptocurrencies), and one that's a trade-off between the two. Exposing those three variants may mean an interface that makes sense exposed separately from other password hashing algorithms.

I liked how SHA1 and MD5 turned out, but it's very reasonable that you'd need to use one of these algorithms in a secure system -- SHA1, which not safe for cryptographic use, is efficient and helpful for things like quickly comparing large files.

BCrypt doesn't have quite the same valid use cases outside of password hashing, so I'd be inclined not to support it. At least, I'd start with Argon2 and wait for someone to request something different.

**Comment by khajavi** [comment]
When I started working on hashing algorithms, I started on the separate package-specific for hashing algorithms. Currently, Bcrypt is somehow finished. 

I agree with your statement that maintaining the BCrypt is useless and there is no reason for other use-cases for it. So if you started working on Argon2 let me know or because I'm about to do it in my spare time don't like to do duplicate work.

**Comment by emarx** [comment]
Not working on Argon — hit it! Trying to build better key management right
now.
